import { createFileRoute, Link } from "@tanstack/react-router";
import { useQuery } from "@tanstack/react-query";
import { useServerFn } from "@tanstack/react-start";
import { Crown, Download, Images, Sparkles } from "lucide-react";
import { Button } from "@/components/ui/button";
import { getMyPremiumStatus } from "@/lib/premium.functions";
import { listGalleryImages } from "@/lib/ai-images.functions";

export const Route = createFileRoute("/_authenticated/ai-gallery")({
  head: () => ({ meta: [{ title: "AI Images Gallery — Nova" }] }),
  component: GalleryPage,
});

function timeAgo(iso: string) {
  const diff = Date.now() - new Date(iso).getTime();
  const m = Math.floor(diff / 60000);
  if (m < 1) return "just now";
  if (m < 60) return `${m}m ago`;
  const h = Math.floor(m / 60);
  if (h < 24) return `${h}h ago`;
  const d = Math.floor(h / 24);
  return `${d}d ago`;
}

function GalleryPage() {
  const getStatus = useServerFn(getMyPremiumStatus);
  const list = useServerFn(listGalleryImages);
  const { data: status, isLoading: sLoading } = useQuery({
    queryKey: ["premium-status"],
    queryFn: () => getStatus({ data: undefined as never }),
  });
  const { data, isLoading, error, refetch } = useQuery({
    queryKey: ["ai-gallery"],
    queryFn: () => list({ data: undefined as never }),
    enabled: !!status?.isPremium,
  });

  if (sLoading) {
    return <div className="mx-auto max-w-2xl px-4 py-16 text-center text-sm text-muted-foreground">Loading…</div>;
  }

  if (!status?.isPremium) {
    return (
      <div className="mx-auto max-w-2xl px-4 py-12 sm:px-6">
        <div className="rounded-3xl border border-border/60 bg-card p-8 text-center">
          <Crown className="mx-auto h-10 w-10 text-primary" />
          <h1 className="mt-3 font-display text-2xl font-bold">Gallery is Premium-only</h1>
          <p className="mt-2 text-sm text-muted-foreground">
            Upgrade to view and download AI images shared by other premium members.
          </p>
          <Button asChild className="mt-6 rounded-full" size="lg">
            <Link to="/premium">Go Premium</Link>
          </Button>
        </div>
      </div>
    );
  }

  return (
    <div className="mx-auto max-w-7xl px-4 py-8 sm:px-6">
      <div className="flex flex-wrap items-center gap-2">
        <Images className="h-5 w-5 text-primary" />
        <h1 className="font-display text-2xl font-bold">AI Images Gallery</h1>
        <Button asChild size="sm" className="ml-auto rounded-full">
          <Link to="/ai-image"><Sparkles className="mr-1.5 h-4 w-4" /> Create</Link>
        </Button>
      </div>
      <p className="mt-1 text-sm text-muted-foreground">All images generated by premium members.</p>

      {isLoading && <p className="mt-6 text-sm text-muted-foreground">Loading gallery…</p>}
      {error && (
        <div className="mt-6 flex items-center justify-between rounded-2xl border border-destructive/30 bg-destructive/5 p-4 text-sm text-destructive">
          <span>Couldn't load gallery.</span>
          <Button size="sm" variant="outline" onClick={() => refetch()}>Retry</Button>
        </div>
      )}
      {data && data.length === 0 && (
        <p className="mt-8 text-center text-sm text-muted-foreground">No images yet. Be the first to create one!</p>
      )}
      {data && data.length > 0 && (
        <div className="mt-6 grid grid-cols-1 gap-4 sm:grid-cols-2 lg:grid-cols-3 xl:grid-cols-4">
          {data.map((img) => (
            <figure key={img.id} className="overflow-hidden rounded-2xl border border-border/60 bg-card">
              <img src={img.url} alt={img.prompt} loading="lazy" className="aspect-square w-full object-cover" />
              <figcaption className="space-y-2 p-3">
                <p className="line-clamp-2 text-sm font-medium">{img.prompt}</p>
                <div className="flex items-center justify-between text-xs text-muted-foreground">
                  <span className="truncate">by {img.creatorName}</span>
                  <span>{timeAgo(img.createdAt)}</span>
                </div>
                <a
                  href={img.url}
                  download={`nova-${img.id}.png`}
                  className="inline-flex w-full items-center justify-center gap-1 rounded-full bg-primary px-3 py-1.5 text-xs font-medium text-primary-foreground hover:opacity-90"
                >
                  <Download className="h-3.5 w-3.5" /> Download
                </a>
              </figcaption>
            </figure>
          ))}
        </div>
      )}
    </div>
  );
}
