/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as GamesRouteImport } from './routes/games'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AppsRouteImport } from './routes/apps'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AppSlugRouteImport } from './routes/app.$slug'
import { Route as AuthenticatedPremiumRouteImport } from './routes/_authenticated/premium'
import { Route as AuthenticatedPaymentCallbackRouteImport } from './routes/_authenticated/payment-callback'
import { Route as AuthenticatedLibraryRouteImport } from './routes/_authenticated/library'
import { Route as AuthenticatedAiImageRouteImport } from './routes/_authenticated/ai-image'
import { Route as ApiPublicPaystackWebhookRouteImport } from './routes/api/public/paystack-webhook'

const GamesRoute = GamesRouteImport.update({
  id: '/games',
  path: '/games',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AppsRoute = AppsRouteImport.update({
  id: '/apps',
  path: '/apps',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AppSlugRoute = AppSlugRouteImport.update({
  id: '/app/$slug',
  path: '/app/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedPremiumRoute = AuthenticatedPremiumRouteImport.update({
  id: '/premium',
  path: '/premium',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedPaymentCallbackRoute =
  AuthenticatedPaymentCallbackRouteImport.update({
    id: '/payment-callback',
    path: '/payment-callback',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedLibraryRoute = AuthenticatedLibraryRouteImport.update({
  id: '/library',
  path: '/library',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedAiImageRoute = AuthenticatedAiImageRouteImport.update({
  id: '/ai-image',
  path: '/ai-image',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const ApiPublicPaystackWebhookRoute =
  ApiPublicPaystackWebhookRouteImport.update({
    id: '/api/public/paystack-webhook',
    path: '/api/public/paystack-webhook',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/apps': typeof AppsRoute
  '/auth': typeof AuthRoute
  '/games': typeof GamesRoute
  '/ai-image': typeof AuthenticatedAiImageRoute
  '/library': typeof AuthenticatedLibraryRoute
  '/payment-callback': typeof AuthenticatedPaymentCallbackRoute
  '/premium': typeof AuthenticatedPremiumRoute
  '/app/$slug': typeof AppSlugRoute
  '/api/public/paystack-webhook': typeof ApiPublicPaystackWebhookRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/apps': typeof AppsRoute
  '/auth': typeof AuthRoute
  '/games': typeof GamesRoute
  '/ai-image': typeof AuthenticatedAiImageRoute
  '/library': typeof AuthenticatedLibraryRoute
  '/payment-callback': typeof AuthenticatedPaymentCallbackRoute
  '/premium': typeof AuthenticatedPremiumRoute
  '/app/$slug': typeof AppSlugRoute
  '/api/public/paystack-webhook': typeof ApiPublicPaystackWebhookRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/apps': typeof AppsRoute
  '/auth': typeof AuthRoute
  '/games': typeof GamesRoute
  '/_authenticated/ai-image': typeof AuthenticatedAiImageRoute
  '/_authenticated/library': typeof AuthenticatedLibraryRoute
  '/_authenticated/payment-callback': typeof AuthenticatedPaymentCallbackRoute
  '/_authenticated/premium': typeof AuthenticatedPremiumRoute
  '/app/$slug': typeof AppSlugRoute
  '/api/public/paystack-webhook': typeof ApiPublicPaystackWebhookRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/apps'
    | '/auth'
    | '/games'
    | '/ai-image'
    | '/library'
    | '/payment-callback'
    | '/premium'
    | '/app/$slug'
    | '/api/public/paystack-webhook'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/apps'
    | '/auth'
    | '/games'
    | '/ai-image'
    | '/library'
    | '/payment-callback'
    | '/premium'
    | '/app/$slug'
    | '/api/public/paystack-webhook'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/apps'
    | '/auth'
    | '/games'
    | '/_authenticated/ai-image'
    | '/_authenticated/library'
    | '/_authenticated/payment-callback'
    | '/_authenticated/premium'
    | '/app/$slug'
    | '/api/public/paystack-webhook'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  AppsRoute: typeof AppsRoute
  AuthRoute: typeof AuthRoute
  GamesRoute: typeof GamesRoute
  AppSlugRoute: typeof AppSlugRoute
  ApiPublicPaystackWebhookRoute: typeof ApiPublicPaystackWebhookRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/games': {
      id: '/games'
      path: '/games'
      fullPath: '/games'
      preLoaderRoute: typeof GamesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/apps': {
      id: '/apps'
      path: '/apps'
      fullPath: '/apps'
      preLoaderRoute: typeof AppsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app/$slug': {
      id: '/app/$slug'
      path: '/app/$slug'
      fullPath: '/app/$slug'
      preLoaderRoute: typeof AppSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/premium': {
      id: '/_authenticated/premium'
      path: '/premium'
      fullPath: '/premium'
      preLoaderRoute: typeof AuthenticatedPremiumRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/payment-callback': {
      id: '/_authenticated/payment-callback'
      path: '/payment-callback'
      fullPath: '/payment-callback'
      preLoaderRoute: typeof AuthenticatedPaymentCallbackRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/library': {
      id: '/_authenticated/library'
      path: '/library'
      fullPath: '/library'
      preLoaderRoute: typeof AuthenticatedLibraryRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/ai-image': {
      id: '/_authenticated/ai-image'
      path: '/ai-image'
      fullPath: '/ai-image'
      preLoaderRoute: typeof AuthenticatedAiImageRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/api/public/paystack-webhook': {
      id: '/api/public/paystack-webhook'
      path: '/api/public/paystack-webhook'
      fullPath: '/api/public/paystack-webhook'
      preLoaderRoute: typeof ApiPublicPaystackWebhookRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface AuthenticatedRouteRouteChildren {
  AuthenticatedAiImageRoute: typeof AuthenticatedAiImageRoute
  AuthenticatedLibraryRoute: typeof AuthenticatedLibraryRoute
  AuthenticatedPaymentCallbackRoute: typeof AuthenticatedPaymentCallbackRoute
  AuthenticatedPremiumRoute: typeof AuthenticatedPremiumRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedAiImageRoute: AuthenticatedAiImageRoute,
  AuthenticatedLibraryRoute: AuthenticatedLibraryRoute,
  AuthenticatedPaymentCallbackRoute: AuthenticatedPaymentCallbackRoute,
  AuthenticatedPremiumRoute: AuthenticatedPremiumRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  AppsRoute: AppsRoute,
  AuthRoute: AuthRoute,
  GamesRoute: GamesRoute,
  AppSlugRoute: AppSlugRoute,
  ApiPublicPaystackWebhookRoute: ApiPublicPaystackWebhookRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
